# Generated by Django 4.2.3 on 2023-07-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
