# Generated by Django 4.2.3 on 2023-08-03 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
