# Generated by Django 4.2.3 on 2023-08-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
